"""Frozen enums for the v2.2A Run Checkpoint Contract (ADR-0016)."""

from enum import Enum


class CheckpointStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    SUSPENDED = "SUSPENDED"
    WAITING_USER = "WAITING_USER"
    FAILED_RECOVERABLE = "FAILED_RECOVERABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ResumeDisposition(str, Enum):
    ALLOW = "ALLOW"
    REQUIRE_CLARIFICATION = "REQUIRE_CLARIFICATION"
    REJECT = "REJECT"


class ResumeAction(str, Enum):
    RESUME_EXACT = "RESUME_EXACT"
    REPLAY_FROM_STAGE = "REPLAY_FROM_STAGE"
    REPLAN_FROM_CHECKPOINT = "REPLAN_FROM_CHECKPOINT"
    ABANDON_AND_RESTART = "ABANDON_AND_RESTART"


class SideEffectState(str, Enum):
    NONE = "NONE"
    NOT_STARTED = "NOT_STARTED"
    STARTED = "STARTED"
    COMMITTED = "COMMITTED"
    FAILED_BEFORE_COMMIT = "FAILED_BEFORE_COMMIT"
    FAILED_AFTER_COMMIT = "FAILED_AFTER_COMMIT"
    COMPENSATED = "COMPENSATED"
    UNKNOWN = "UNKNOWN"


class GuardStatus(str, Enum):
    VERIFIED = "VERIFIED"
    UNKNOWN = "UNKNOWN"
    MISMATCH = "MISMATCH"
    MISSING = "MISSING"


class ResumeReasonCode(str, Enum):
    ALLOWED_EXACT = "ALLOWED_EXACT"
    ALLOWED_REPLAY = "ALLOWED_REPLAY"
    ALLOWED_REPLAN = "ALLOWED_REPLAN"
    ALLOWED_ABANDON = "ALLOWED_ABANDON"

    AMBIGUOUS_RUN = "AMBIGUOUS_RUN"
    TARGET_CONFLICT = "TARGET_CONFLICT"
    EXTERNAL_STATE_UNKNOWN = "EXTERNAL_STATE_UNKNOWN"
    EXTERNAL_STATE_MISMATCH = "EXTERNAL_STATE_MISMATCH"
    MISSING_PERMISSION = "MISSING_PERMISSION"

    CHECKPOINT_INVALIDATED = "CHECKPOINT_INVALIDATED"
    TERMINAL_CHECKPOINT = "TERMINAL_CHECKPOINT"
    NO_RESUMABLE_POSITION = "NO_RESUMABLE_POSITION"
    NO_RUN_MATCH = "NO_RUN_MATCH"
    MISSING_CONTEXT = "MISSING_CONTEXT"

    SCHEMA_INCOMPATIBLE = "SCHEMA_INCOMPATIBLE"
    CONTRACT_INCOMPATIBLE = "CONTRACT_INCOMPATIBLE"
    WORKFLOW_INCOMPATIBLE = "WORKFLOW_INCOMPATIBLE"
    PLAN_INCOMPATIBLE = "PLAN_INCOMPATIBLE"

    NON_IDEMPOTENT_STAGE = "NON_IDEMPOTENT_STAGE"
    DUPLICATE_SIDE_EFFECT = "DUPLICATE_SIDE_EFFECT"
    UNKNOWN_SIDE_EFFECT = "UNKNOWN_SIDE_EFFECT"
    SIDE_EFFECT_IN_PROGRESS = "SIDE_EFFECT_IN_PROGRESS"
    INVALID_REQUESTED_STAGE = "INVALID_REQUESTED_STAGE"


__all__ = [
    "CheckpointStatus",
    "ResumeDisposition",
    "ResumeAction",
    "SideEffectState",
    "GuardStatus",
    "ResumeReasonCode",
]
